//! Pairing: enrolling a device against a short-lived, single-use code.
//!
//! Flow, normatively described in `docs/protocol.md` § 6.2:
//!
//! 1. The daemon displays a code (`drdshd pair`) with [`crate::PAIRING_CODE_TTL`] on the clock.
//! 2. The client and daemon run a balanced PAKE keyed by that code. Neither sends the code,
//!    and neither sends anything that allows an offline guess against it.
//! 3. Over the resulting key, the client proves possession of a freshly generated identity
//!    key and the daemon returns the enrolment receipt. The daemon stores the device's
//!    public key; the client stores its private key.
//! 4. The code is burned — single use, even on failure (project definition § 9.4).
//!
//! ## Why SPAKE2 and not "hash the code"
//!
//! The code is 40 bits and it is typed into a device that reaches the daemon *through the
//! relay*. A hash-the-code design would let the relay — or anyone who recorded the
//! exchange — mount an offline dictionary against 2⁴⁰ possibilities, which is minutes of
//! work. SPAKE2 authenticates the code without ever putting anything on the wire that
//! permits an offline guess, and the key it produces is forward-secret.
//!
//! ## What this module deliberately does not decide
//!
//! It does not decide *who* may start a pairing, how attempts are rate-limited, or where a
//! registry is stored. Those are policy and live with the daemon; what lives here is the
//! part that must be identical on both ends, plus the lifecycle rules that are security
//! properties rather than preferences (single use, expiry, ordering).
//!
//! ## Browser support is a second implementation of *this* construction
//!
//! There is no SPAKE2 in WebCrypto and no way to reach the Ed25519 group from a browser
//! without writing the group arithmetic out. The browser therefore re-expresses the
//! arithmetic — `apps/pwa/src/ed25519.ts` and `spake2.ts` — over the *same* protocol: the same
//! blinding points, the same password-to-scalar derivation, the same transcript. It is not a
//! reduced handshake, because a second protocol would have different security properties; it
//! is the same one, and `packages/crypto/conformance/pairing-vectors.json` (generated by
//! `crates/dr-dsh-crypto/tests/pairing_vectors.rs`) pins the two byte for byte. `docs/security.md`
//! § 3.2 states what the browser implementation does not guarantee.
//!
//! ## Where the room key comes from
//!
//! [The receipt is sealed, not announced.](PairedDevice::seal_room_key) The key a device must
//! serve from is the daemon's long-lived room key, and the pairing room's transport root is a
//! published constant — so the receipt carries that key encrypted under the key the PAKE
//! produced, and the client opens it with [`open_room_key`]. Announcing the PAKE output
//! instead, which this module did at first, gave every freshly paired device a key no daemon
//! served.

use zeroize::Zeroizing;

use crate::device::{DeviceError, DevicePublicKey};
use crate::labels;

/// A displayed, single-use pairing code.
///
/// The code is the human-transported form of the PAKE secret. It is rendered in groups to
/// make transcription less error-prone, and its grouping is removed before it is used as key
/// material.
#[derive(Clone)]
pub struct PairingCode {
    /// Raw secret bytes. Zeroized on drop.
    secret: Zeroizing<[u8; crate::PAIRING_SECRET_LEN]>,
}

impl PairingCode {
    /// Wraps raw secret bytes.
    #[must_use]
    pub fn from_secret(secret: [u8; crate::PAIRING_SECRET_LEN]) -> Self {
        Self {
            secret: Zeroizing::new(secret),
        }
    }

    /// Draws a fresh code.
    ///
    /// Five bytes exactly, so the displayed form is the 40 bits `docs/security.md` claims
    /// and not whatever a rejection sampler happened to leave behind.
    #[must_use]
    pub fn generate() -> Self {
        use rand::RngCore as _;
        let mut secret = [0_u8; crate::PAIRING_SECRET_LEN];
        rand::rng().fill_bytes(&mut secret);
        Self::from_secret(secret)
    }

    /// Renders the code for display, e.g. `7Q4M-2XKP-9T`.
    #[must_use]
    pub fn display_form(&self) -> String {
        // Grouping is presentation only; the PAKE consumes `secret` directly.
        crate::pairing_display(self.secret.as_ref())
    }

    /// Borrows the raw secret for the PAKE.
    #[must_use]
    pub fn secret(&self) -> &[u8; crate::PAIRING_SECRET_LEN] {
        &self.secret
    }
}

impl core::fmt::Debug for PairingCode {
    /// Never prints the secret: this type ends up in logs by accident otherwise.
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str("PairingCode(redacted)")
    }
}

/// Identities bound into the SPAKE2 transcript.
///
/// Both ends must pass these in the same order (`id_a` = client, `id_b` = daemon), or the
/// two sides derive different keys and the failure looks like a wrong code. Binding the
/// transcript is what stops a message from one pairing being replayed into another.
const IDENTITY_CLIENT: &[u8] = b"dsh-remote/v1/pairing/client";
const IDENTITY_DAEMON: &[u8] = b"dsh-remote/v1/pairing/daemon";

/// Length of a SPAKE2 message on the wire, for the Ed25519 group: one side byte plus one
/// compressed point.
#[must_use]
pub fn spake2_message_len() -> usize {
    1 + <spake2::Ed25519Group as spake2::Group>::element_length()
}

/// The stretch a code is put through before a rendezvous room is derived from it.
///
/// It lives here rather than in the daemon because it is key derivation, and because the
/// cross-language vectors have to pin it: a browser that derived the rendezvous room
/// differently would wait in a room nobody serves, and the user would be told "no daemon is
/// serving this room" instead of "your code is wrong".
///
/// One-way, so a relay that logs room ids learns nothing that helps guess the code. It is
/// nonetheless only 40 bits of input: the room id is not a secret and is not what
/// authenticates the exchange. SPAKE2 is.
#[must_use]
pub fn rendezvous_root(code: &PairingCode) -> [u8; crate::SESSION_KEY_LEN] {
    let mut stretched = [0_u8; crate::SESSION_KEY_LEN];
    let hkdf = hkdf::Hkdf::<sha2::Sha256>::new(None, code.secret());
    // 32 bytes is a valid HKDF output length, so this cannot fail; the fallback keeps the
    // function total rather than panicking.
    if hkdf.expand(labels::PAIRING_ROOT, &mut stretched).is_err() {
        return [0_u8; crate::SESSION_KEY_LEN];
    }
    stretched
}

/// The room a pairing exchange happens in, derived one-way from the code.
///
/// Separate from the room the daemon will serve: the pairing room is a rendezvous a relay can
/// log without learning anything it can reuse, and it stops being interesting the moment the
/// code expires.
#[must_use]
pub fn rendezvous_room(code: &PairingCode) -> String {
    crate::room_id_for(&rendezvous_root(code))
}

/// The provisional root a pairing room's frames are sealed under.
///
/// A **constant**, and that is the fix for a real flaw rather than a simplification. It used
/// to be derived from the code, which meant two ends holding different codes could not open
/// each other's frames at all: a mistyped code failed inside the session handshake, which has
/// no way to say why, and the client sat there until a timeout. The most likely user error
/// produced a hang instead of a sentence.
///
/// It is safe to be public because it protects nothing. The room id is derived from the code
/// (one-way) and the relay sees it; a code-derived *sealing* key added no secrecy — anyone who
/// could guess the code could derive it anyway — while removing the ability to tell a wrong
/// code from a broken connection. Authentication comes from SPAKE2, which is checked under
/// this transport and refuses a bad code by name.
#[must_use]
pub fn transport_root() -> [u8; crate::SESSION_KEY_LEN] {
    use sha2::Digest as _;
    let mut root = [0_u8; crate::SESSION_KEY_LEN];
    let mut hasher = sha2::Sha256::new();
    hasher.update(labels::PAIRING_ROOT);
    hasher.update(b"transport");
    root.copy_from_slice(&hasher.finalize());
    root
}

/// Why a pairing attempt failed.
#[derive(Debug, thiserror::Error)]
pub enum PairingError {
    /// The exchange was driven out of order.
    ///
    /// A `pair_begin` message must be consumed before a `pair_finish`, and a session may
    /// only be finished once. Driving it twice is a protocol violation, and answering it
    /// with a fresh exchange would hand an attacker a second guess against the same code.
    #[error("the pairing exchange was used out of order: {0}")]
    OutOfOrder(&'static str),
    /// The supplied code has expired.
    #[error("the pairing code has expired")]
    Expired,
    /// The code was already consumed, by this attempt or an earlier one.
    #[error("the pairing code has already been used")]
    AlreadyUsed,
    /// The peer's SPAKE2 message was not the expected shape.
    #[error("the peer's pairing message is malformed")]
    MalformedMessage,
    /// The peer could not complete the PAKE, which is what a wrong code looks like.
    ///
    /// This is the *only* thing a wrong code produces. The failure is deliberately not
    /// distinguishable from a malformed message at the outer layer: telling a guesser
    /// "right length, wrong code" is a free oracle.
    #[error("the pairing code does not match")]
    CodeMismatch,
    /// The client's possession proof did not verify.
    #[error("the device did not prove possession of its key")]
    ConfirmationFailed,
    /// The room key could not be sealed into, or opened from, an enrolment receipt.
    ///
    /// One variant for both directions, and deliberately without detail: on the client this
    /// means "the receipt was not produced by the peer that completed the PAKE", which is a
    /// substituted or corrupted receipt and nothing more specific than that.
    #[error("the enrolment receipt could not be opened")]
    Receipt,
    /// The client's identity key was not usable.
    #[error("the device's identity key is not usable: {0}")]
    Device(#[from] DeviceError),
}

/// A generated code plus the clock reading it was created at.
///
/// Time is passed in rather than read here so that expiry is testable without sleeping, and
/// so a daemon with a monotonic clock can supply it. A pairing code's lifetime is a security
/// property, and a property that can only be tested by waiting five minutes is a property
/// that stops being tested.
#[derive(Debug)]
pub struct PendingCode {
    code: PairingCode,
    created_at: std::time::Instant,
    ttl: std::time::Duration,
    used: bool,
}

impl PendingCode {
    /// Registers a code that is valid for [`crate::PAIRING_CODE_TTL`].
    #[must_use]
    pub fn new(code: PairingCode) -> Self {
        Self::with_ttl(code, crate::PAIRING_CODE_TTL)
    }

    /// Registers a code with an explicit lifetime.
    #[must_use]
    pub fn with_ttl(code: PairingCode, ttl: std::time::Duration) -> Self {
        Self {
            code,
            created_at: std::time::Instant::now(),
            ttl,
            used: false,
        }
    }

    /// The code, for display.
    #[must_use]
    pub fn code(&self) -> &PairingCode {
        &self.code
    }

    /// Whether the code has expired at `now`.
    #[must_use]
    pub fn is_expired(&self) -> bool {
        self.created_at.elapsed() >= self.ttl
    }

    /// Whether the code has been consumed.
    #[must_use]
    pub fn is_used(&self) -> bool {
        self.used
    }

    /// How long is left on the code, or zero once it has expired.
    #[must_use]
    pub fn remaining(&self) -> std::time::Duration {
        self.ttl.saturating_sub(self.created_at.elapsed())
    }

    /// Consumes the code, refusing an expired or already-used one.
    ///
    /// Burning on **entry** rather than on success is the whole anti-online-guessing
    /// property: a wrong code costs the attacker a fresh code, so 2⁴⁰ entropy is not
    /// reduced by retrying against one code. It also means a failed attempt cannot be
    /// retried by the honest user — which is correct, if annoying: the daemon prints a new
    /// code.
    ///
    /// # Errors
    ///
    /// Returns [`PairingError::AlreadyUsed`] or [`PairingError::Expired`].
    pub fn consume(&mut self) -> Result<(), PairingError> {
        if self.used {
            return Err(PairingError::AlreadyUsed);
        }
        if self.is_expired() {
            // Marked used as well: an expired code must not become usable again if it is
            // somehow held past its lifetime.
            self.used = true;
            return Err(PairingError::Expired);
        }
        self.used = true;
        Ok(())
    }
}

/// The daemon's half of a pairing exchange.
///
/// Holds the intermediate SPAKE2 state. [`Self::finish`] consumes it, so a second attempt
/// against the same exchange is a type error rather than a runtime check that someone can
/// forget.
pub struct DaemonPairing {
    /// `Option` because `finish` takes the inner value out; the state machine admits
    /// exactly one finish, and this is what enforces it without a panic path.
    spake: Option<spake2::Spake2<spake2::Ed25519Group>>,
}

impl DaemonPairing {
    /// Starts the daemon's half and returns the message to send to the client.
    ///
    /// The caller is responsible for having consumed the pending code first: that is the
    /// point at which an attempt costs the attacker a code, and doing it here would make
    /// the burn conditional on SPAKE2 succeeding, which is the opposite of the rule.
    #[must_use]
    pub fn begin(code: &PairingCode) -> (Self, Vec<u8>) {
        let password = spake2::Password::new(code.secret().as_slice());
        let id_a = spake2::Identity::new(IDENTITY_CLIENT);
        let id_b = spake2::Identity::new(IDENTITY_DAEMON);
        let (spake, message) =
            spake2::Spake2::<spake2::Ed25519Group>::start_b(&password, &id_a, &id_b);
        (Self { spake: Some(spake) }, message)
    }

    /// Completes the PAKE and verifies the client's possession proof.
    ///
    /// `confirm` is the client's signature over [`enrolment_message`] for the public key it
    /// is enrolling. Verifying it over the derived PAKE key is what turns "someone who saw
    /// the code" into "someone who also holds the identity they are claiming": the proof is
    /// checked before the key is returned to the caller, so there is no path where an
    /// unverified key reaches a registry.
    ///
    /// # Errors
    ///
    /// Returns [`PairingError::CodeMismatch`] when the peer used a different code, and
    /// [`PairingError::ConfirmationFailed`] when the proof does not verify.
    pub fn finish(
        self,
        peer_message: &[u8],
        public_key: &[u8; crate::DEVICE_PUBLIC_KEY_LEN],
        confirm: &[u8],
    ) -> Result<PairedDevice, PairingError> {
        let spake = self.spake.ok_or(PairingError::OutOfOrder(
            "this exchange is already finished",
        ))?;
        let key = spake
            .finish(peer_message)
            .map_err(|_| PairingError::CodeMismatch)?;

        // The proof is a MAC under the PAKE key, and that is what makes the code load-bearing.
        // It was a bare Ed25519 signature at first, which verified against the public key the
        // client itself supplied — so a device using the *wrong* code still enrolled, because
        // the signature was self-consistent. A signature proves possession of an identity;
        // only a MAC under the exchanged key proves knowledge of the code, and enrolment
        // needs both.
        let public_key = DevicePublicKey::from_bytes(public_key)?;
        let expected = enrolment_confirmation(&key, &public_key.to_bytes());
        if !constant_time_eq(&expected, confirm) {
            return Err(PairingError::ConfirmationFailed);
        }

        Ok(PairedDevice {
            public_key,
            enrolment_key: derive_pairing_root(&key),
        })
    }
}

/// A successfully enrolled device.
pub struct PairedDevice {
    /// The device's identity, as the daemon will store it.
    pub public_key: DevicePublicKey,
    /// The key the receipt is sealed under.
    enrolment_key: Zeroizing<[u8; crate::SESSION_KEY_LEN]>,
}

impl PairedDevice {
    /// The enrolment key: the symmetric key the receipt is sealed under.
    ///
    /// Handed out deliberately rather than exposed as a field: it is the only key that can
    /// open the room key this daemon sends, and it should be possible to grep for every place
    /// it is read. It is **not** the room key — see [`seal_room_key`] for what happens when
    /// the two are confused.
    #[must_use]
    pub fn enrolment_key(&self) -> &[u8; crate::SESSION_KEY_LEN] {
        &self.enrolment_key
    }

    /// The enrolled device's id.
    #[must_use]
    pub fn device_id(&self) -> crate::device::DeviceId {
        self.public_key.device_id()
    }

    /// Seals the room key this device will serve from.
    ///
    /// The room key is the daemon's own long-lived secret, and the pairing room's transport is
    /// *not* confidential — its root is a published constant, so anything sent over it in the
    /// clear is readable by the relay. It is therefore not sent in the clear: it is sealed
    /// under the enrolment key, which only the two ends of a completed PAKE hold, and bound to
    /// the public key being enrolled so a receipt cannot be moved onto another device.
    ///
    /// # Errors
    ///
    /// Returns [`PairingError::Sealing`] when the AEAD refuses, which would mean the key or the
    /// nonce length is wrong rather than anything about the input.
    #[must_use]
    pub fn seal_room_key(&self, room_key: &[u8; crate::SESSION_KEY_LEN]) -> Vec<u8> {
        let nonce = receipt_nonce();
        self.seal_room_key_with(room_key, &nonce)
    }

    /// [`Self::seal_room_key`] with an explicit nonce, so the vector corpus can pin the bytes.
    #[must_use]
    pub fn seal_room_key_with(
        &self,
        room_key: &[u8; crate::SESSION_KEY_LEN],
        nonce: &[u8; crate::NONCE_LEN],
    ) -> Vec<u8> {
        seal_room_key(
            self.enrolment_key.as_ref(),
            &self.public_key.to_bytes(),
            room_key,
            nonce,
        )
    }
}

impl core::fmt::Debug for PairedDevice {
    /// Prints the device id, never the enrolment key.
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "PairedDevice({})", self.device_id().to_base64url())
    }
}

/// The client's half of a pairing exchange.
///
/// Present so the daemon's half can be tested against something that is not itself, and so
/// a native client has a reference implementation of the same construction. It is not
/// reachable from a browser; see the module docs.
pub struct ClientPairing {
    spake: Option<spake2::Spake2<spake2::Ed25519Group>>,
}

impl ClientPairing {
    /// Starts the client's half and returns the message to send to the daemon.
    #[must_use]
    pub fn begin(code: &PairingCode) -> (Self, Vec<u8>) {
        let password = spake2::Password::new(code.secret().as_slice());
        let id_a = spake2::Identity::new(IDENTITY_CLIENT);
        let id_b = spake2::Identity::new(IDENTITY_DAEMON);
        let (spake, message) =
            spake2::Spake2::<spake2::Ed25519Group>::start_a(&password, &id_a, &id_b);
        (Self { spake: Some(spake) }, message)
    }

    /// Completes the PAKE and returns the root key plus the proof to send.
    ///
    /// Completes the PAKE and returns the exchanged key without building a proof.
    ///
    /// # Errors
    ///
    /// Returns [`PairingError::CodeMismatch`] when the daemon used a different code, which
    /// here only means the peer's message was not a usable SPAKE2 message: a *wrong* code
    /// still produces a key, and it is the proof that later fails. That asymmetry is the
    /// point of a PAKE, and it is why the confirmation is checked under this key.
    pub fn finish_raw(
        self,
        peer_message: &[u8],
        identity: &crate::device::DeviceSecretKey,
    ) -> Result<RawClientKey, PairingError> {
        let spake = self.spake.ok_or(PairingError::OutOfOrder(
            "this exchange is already finished",
        ))?;
        let exchanged = spake
            .finish(peer_message)
            .map_err(|_| PairingError::CodeMismatch)?;
        Ok(RawClientKey {
            exchanged,
            public_key: identity.public().to_bytes(),
        })
    }

    /// # Errors
    ///
    /// Returns [`PairingError::CodeMismatch`] when the daemon used a different code.
    pub fn finish(
        self,
        peer_message: &[u8],
        identity: &crate::device::DeviceSecretKey,
    ) -> Result<ClientEnrolment, PairingError> {
        let raw = self.finish_raw(peer_message, identity)?;
        Ok(ClientEnrolment {
            public_key: raw.public_key,
            confirm: enrolment_confirmation(&raw.exchanged, &raw.public_key),
            enrolment_key: derive_pairing_root(&raw.exchanged),
        })
    }
}

/// What a client sends to finish pairing.
pub struct ClientEnrolment {
    /// The public half of the identity being enrolled.
    pub public_key: [u8; crate::DEVICE_PUBLIC_KEY_LEN],
    /// The possession proof over [`enrolment_message`].
    pub confirm: Vec<u8>,
    enrolment_key: Zeroizing<[u8; crate::SESSION_KEY_LEN]>,
}

impl ClientEnrolment {
    /// The **enrolment key**: what the daemon's receipt is sealed under.
    ///
    /// It is not the room key, and calling it one was a real defect: the daemon announced it
    /// as the key the client should serve from, while the daemon itself served the room key it
    /// was configured with — so a freshly paired device dialled a room nobody served. See
    /// [`seal_room_key`].
    #[must_use]
    pub fn enrolment_key(&self) -> &[u8; crate::SESSION_KEY_LEN] {
        &self.enrolment_key
    }
}

/// The client's half of the exchange, completed.
///
/// Returned by [`ClientPairing::finish_raw`] so that a caller can build its own proof — the
/// property tests need to play an attacker who holds the identity but not the code, and that
/// attacker is only expressible if the raw exchanged key is reachable.
pub struct RawClientKey {
    /// The SPAKE2 output, before it is extracted into a root key.
    pub exchanged: Vec<u8>,
    /// The identity the client used.
    pub public_key: [u8; crate::DEVICE_PUBLIC_KEY_LEN],
}

/// The client's proof that it knows the code *and* holds the identity it is enrolling.
///
/// A MAC under the PAKE key rather than a signature: see [`DaemonPairing::finish`] for why
/// a signature alone was not enough. The public key is bound in so the proof cannot be
/// moved onto a different identity, and the label keeps it distinct from every other value
/// derived from the same key.
#[must_use]
pub fn enrolment_confirmation(
    spake_output: &[u8],
    public_key: &[u8; crate::DEVICE_PUBLIC_KEY_LEN],
) -> Vec<u8> {
    use hmac::Mac as _;
    // `SimpleHmac` rather than `Hmac`: the latter is the fixed-key-size variant, and a
    // SPAKE2 output is a group encoding whose length is the group's business. The fallible
    // constructor is the one that says so, and it cannot fail for a slice of any length.
    let mut mac =
        <hmac::SimpleHmac<sha2::Sha256> as hmac::digest::KeyInit>::new_from_slice(spake_output)
            .unwrap_or_else(|_| unreachable!("SimpleHmac accepts a key of any length"));
    mac.update(labels::ENROLMENT_CONFIRM);
    mac.update(public_key);
    mac.finalize().into_bytes().to_vec()
}

/// Seals a room key into an enrolment receipt.
///
/// Layout: `nonce (12) || AES-256-GCM ciphertext+tag`, with the label and the enrolled public
/// key as additional authenticated data.
///
/// ## Why the room key is not simply announced
///
/// It used to be. `pair_accept` carried `derive_pairing_root(spake_output)` in the clear, over
/// a transport whose root is a **published constant** — so the relay could decrypt it, and the
/// value it decrypted was the key the client would then serve its room from. That is a
/// zero-knowledge break, and it is invisible in a test that only checks the two ends agree.
///
/// The fix is not "encrypt it with something": it is to notice that the receipt has exactly one
/// legitimate reader, the client that just completed the PAKE. The enrolment key is that
/// reader's key, and binding the public key into the AAD keeps a receipt from being replayed
/// onto a different identity enrolled in the same exchange.
#[must_use]
pub fn seal_room_key(
    enrolment_key: &[u8],
    public_key: &[u8; crate::DEVICE_PUBLIC_KEY_LEN],
    room_key: &[u8; crate::SESSION_KEY_LEN],
    nonce: &[u8; crate::NONCE_LEN],
) -> Vec<u8> {
    use aes_gcm::aead::Aead as _;
    use aes_gcm::{Aes256Gcm, KeyInit as _, Nonce};

    // The key comes from HKDF, so its length is fixed; `new_from_slice` cannot fail here.
    let Some(cipher) = Aes256Gcm::new_from_slice(enrolment_key).ok() else {
        return Vec::new();
    };
    let aad = receipt_aad(public_key);
    let sealed = cipher
        .encrypt(
            &Nonce::from(*nonce),
            aes_gcm::aead::Payload {
                msg: room_key,
                aad: &aad,
            },
        )
        .unwrap_or_default();
    let mut out = Vec::with_capacity(crate::NONCE_LEN + sealed.len());
    out.extend_from_slice(nonce);
    out.extend_from_slice(&sealed);
    out
}

/// Opens an enrolment receipt.
///
/// # Errors
///
/// Returns [`PairingError::Receipt`] for anything that is not a receipt this key and identity
/// can open — a truncated blob, a substituted one, or one sealed for another device.
pub fn open_room_key(
    enrolment_key: &[u8],
    public_key: &[u8; crate::DEVICE_PUBLIC_KEY_LEN],
    sealed: &[u8],
) -> Result<Zeroizing<[u8; crate::SESSION_KEY_LEN]>, PairingError> {
    use aes_gcm::aead::Aead as _;
    use aes_gcm::{Aes256Gcm, KeyInit as _, Nonce};

    let body = sealed
        .get(crate::NONCE_LEN..)
        .ok_or(PairingError::Receipt)?;
    let nonce: [u8; crate::NONCE_LEN] = sealed
        .get(..crate::NONCE_LEN)
        .and_then(|slice| slice.try_into().ok())
        .ok_or(PairingError::Receipt)?;
    let Some(cipher) = Aes256Gcm::new_from_slice(enrolment_key).ok() else {
        return Err(PairingError::Receipt);
    };
    let aad = receipt_aad(public_key);
    let opened = cipher
        .decrypt(
            &Nonce::from(nonce),
            aes_gcm::aead::Payload {
                msg: body,
                aad: &aad,
            },
        )
        .map_err(|_| PairingError::Receipt)?;
    let key: [u8; crate::SESSION_KEY_LEN] = opened
        .as_slice()
        .try_into()
        .map_err(|_| PairingError::Receipt)?;
    Ok(Zeroizing::new(key))
}

/// The additional authenticated data of a receipt: the label and the enrolled identity.
fn receipt_aad(public_key: &[u8; crate::DEVICE_PUBLIC_KEY_LEN]) -> Vec<u8> {
    let mut aad = Vec::with_capacity(labels::ENROLMENT_SEAL.len() + public_key.len());
    aad.extend_from_slice(labels::ENROLMENT_SEAL);
    aad.extend_from_slice(public_key);
    aad
}

/// Draws a fresh nonce for a receipt.
#[must_use]
pub fn receipt_nonce() -> [u8; crate::NONCE_LEN] {
    use rand::RngCore as _;
    let mut nonce = [0_u8; crate::NONCE_LEN];
    rand::rng().fill_bytes(&mut nonce);
    nonce
}

/// Compares two byte strings without leaking where they differ.
///
/// A confirmation is attacker-supplied, and a comparison that returns early turns "guess the
/// whole MAC" into "guess it one byte at a time".
fn constant_time_eq(expected: &[u8], presented: &[u8]) -> bool {
    use subtle::ConstantTimeEq as _;
    if expected.len() != presented.len() {
        return false;
    }
    expected.ct_eq(presented).into()
}

/// Derives the room root key from the raw SPAKE2 output.
///
/// Extracted rather than used directly: SPAKE2's output is a group element encoding whose
/// distribution is the group's business, and HKDF is what turns it into 32 uniform bytes
/// with a label that pins *which* protocol version derived it.
///
/// Public because a client in another language has to perform exactly this step, and the
/// cross-language vectors pin *this* implementation rather than a copy of it.
#[must_use]
pub fn derive_pairing_root(spake_output: &[u8]) -> Zeroizing<[u8; crate::SESSION_KEY_LEN]> {
    let hkdf = hkdf::Hkdf::<sha2::Sha256>::new(None, spake_output);
    let mut root = Zeroizing::new([0_u8; crate::SESSION_KEY_LEN]);
    hkdf.expand(labels::PAIRING_ROOT, root.as_mut())
        .unwrap_or_else(|_| unreachable!("32 bytes is a valid HKDF output length"));
    root
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::device::DeviceSecretKey;

    type TestResult = Result<(), Box<dyn std::error::Error>>;

    /// Runs one full exchange between a client and a daemon holding the same code.
    fn exchange(code: &PairingCode) -> Result<(PairedDevice, ClientEnrolment), PairingError> {
        let identity = DeviceSecretKey::generate();
        let (daemon, daemon_message) = DaemonPairing::begin(code);
        let (client, client_message) = ClientPairing::begin(code);
        let enrolment = client.finish(&daemon_message, &identity)?;
        let paired = daemon.finish(&client_message, &enrolment.public_key, &enrolment.confirm)?;
        Ok((paired, enrolment))
    }

    #[test]
    fn both_ends_derive_the_same_enrolment_key() -> TestResult {
        let code = PairingCode::generate();
        let (paired, enrolment) = exchange(&code)?;
        assert_eq!(
            paired.enrolment_key(),
            enrolment.enrolment_key(),
            "the two ends must agree on the key the receipt is sealed under"
        );
        assert_ne!(
            paired.enrolment_key(),
            &[0_u8; crate::SESSION_KEY_LEN],
            "a derived key must not be the all-zero value"
        );
        Ok(())
    }

    #[test]
    fn the_room_key_survives_the_receipt_and_nothing_else_opens_it() -> TestResult {
        let code = PairingCode::generate();
        let (paired, enrolment) = exchange(&code)?;
        let room_key = [9_u8; crate::SESSION_KEY_LEN];

        let sealed = paired.seal_room_key(&room_key);
        let opened = open_room_key(enrolment.enrolment_key(), &enrolment.public_key, &sealed)?;
        assert_eq!(
            *opened, room_key,
            "the receipt is how the device learns the room key"
        );

        // The room key must not be in the receipt: the pairing room's transport root is a
        // published constant, so anything sent in the clear there is readable by the relay.
        assert!(
            !sealed
                .windows(room_key.len())
                .any(|window| window == room_key),
            "the room key must not appear verbatim in the receipt"
        );

        // A different enrolment key is a different exchange and must not open this receipt.
        let other = [7_u8; crate::SESSION_KEY_LEN];
        assert!(matches!(
            open_room_key(&other, &enrolment.public_key, &sealed),
            Err(PairingError::Receipt)
        ));

        // The receipt is bound to the identity it was sealed for.
        let other_identity = DeviceSecretKey::generate();
        assert!(matches!(
            open_room_key(
                enrolment.enrolment_key(),
                &other_identity.public().to_bytes(),
                &sealed
            ),
            Err(PairingError::Receipt)
        ));

        // Truncated and flipped receipts are refused rather than half-read.
        assert!(matches!(
            open_room_key(
                enrolment.enrolment_key(),
                &enrolment.public_key,
                &sealed[..4]
            ),
            Err(PairingError::Receipt)
        ));
        let mut flipped = sealed.clone();
        if let Some(last) = flipped.last_mut() {
            *last ^= 0x01;
        }
        assert!(matches!(
            open_room_key(enrolment.enrolment_key(), &enrolment.public_key, &flipped),
            Err(PairingError::Receipt)
        ));
        Ok(())
    }

    #[test]
    fn two_receipts_for_the_same_room_key_differ() -> TestResult {
        // A fresh nonce per receipt: a repeated one would make two enrolments of the same room
        // key produce identical ciphertext, which is a correlation a relay can see.
        let code = PairingCode::generate();
        let (paired, _enrolment) = exchange(&code)?;
        let room_key = [3_u8; crate::SESSION_KEY_LEN];
        assert_ne!(
            paired.seal_room_key(&room_key),
            paired.seal_room_key(&room_key)
        );
        Ok(())
    }

    #[test]
    fn the_enrolled_key_is_the_one_the_client_holds() -> TestResult {
        let code = PairingCode::generate();
        let identity = DeviceSecretKey::generate();
        let (daemon, daemon_message) = DaemonPairing::begin(&code);
        let (client, client_message) = ClientPairing::begin(&code);
        let enrolment = client.finish(&daemon_message, &identity)?;
        let paired = daemon.finish(&client_message, &enrolment.public_key, &enrolment.confirm)?;

        // The daemon stored the public half of the identity the client actually holds, and
        // the id both ends compute from it agrees.
        assert_eq!(paired.public_key, identity.public());
        assert_eq!(paired.device_id(), identity.public().device_id());
        Ok(())
    }

    #[test]
    fn a_different_code_cannot_complete_the_exchange() -> TestResult {
        // The property that makes 40 bits enough: a wrong code yields a different key, so
        // the possession proof cannot verify. Nothing on the wire reveals *how* wrong.
        let daemon_code = PairingCode::from_secret([7, 7, 7, 7, 7]);
        let client_code = PairingCode::from_secret([7, 7, 7, 7, 8]);
        let identity = DeviceSecretKey::generate();

        let (daemon, daemon_message) = DaemonPairing::begin(&daemon_code);
        let (client, client_message) = ClientPairing::begin(&client_code);
        let enrolment = client.finish(&daemon_message, &identity)?;

        let outcome = daemon.finish(&client_message, &enrolment.public_key, &enrolment.confirm);
        assert!(
            matches!(outcome, Err(PairingError::ConfirmationFailed)),
            "a wrong code must not enrol a device: got {:?}",
            outcome.map(|p| p.device_id().to_base64url())
        );
        Ok(())
    }

    #[test]
    fn an_attacker_who_holds_a_key_but_not_the_code_is_refused() -> TestResult {
        // This is the test the first version of `finish` failed, and it is the reason the
        // proof is a MAC rather than a signature. A signature only proves possession of an
        // identity — which the attacker has, because it can generate its own key. The code
        // is load-bearing only if the proof is computed *under the exchanged key*, so this
        // plays an attacker that completes the PAKE with the wrong code and then supplies a
        // perfectly valid self-signature. Only the MAC check refuses it.
        let daemon_code = PairingCode::from_secret([9, 9, 9, 9, 9]);
        let attacker_code = PairingCode::from_secret([9, 9, 9, 9, 8]);
        let identity = DeviceSecretKey::generate();

        let (daemon, daemon_message) = DaemonPairing::begin(&daemon_code);
        let (attacker, attacker_message) = ClientPairing::begin(&attacker_code);
        let raw = attacker.finish_raw(&daemon_message, &identity)?;

        // A confirmation that satisfies a naive "is this a signature by the enrolled key"
        // check: it is exactly that, and it verifies. It is not a MAC under the exchanged
        // key, which is the only thing that proves knowledge of the code.
        let self_signed = identity.sign(&raw.public_key).to_vec();
        assert!(
            identity
                .public()
                .verify(&raw.public_key, &self_signed)
                .is_ok(),
            "the self-signature must be valid, or this test proves nothing"
        );

        let outcome = daemon.finish(&attacker_message, &raw.public_key, &self_signed);
        assert!(
            matches!(outcome, Err(PairingError::ConfirmationFailed)),
            "a wrong code must not enrol a device, whatever proof shape it presents"
        );
        Ok(())
    }

    #[test]
    fn a_forged_or_tampered_confirmation_is_refused() -> TestResult {
        // The proof is a MAC under the key the PAKE produced, so guessing it is a 2^-256
        // proposition and it cannot be moved onto another identity.
        let code = PairingCode::generate();
        let identity = DeviceSecretKey::generate();
        let (daemon, daemon_message) = DaemonPairing::begin(&code);
        let (client, client_message) = ClientPairing::begin(&code);
        let enrolment = client.finish(&daemon_message, &identity)?;

        // One flipped bit in the proof.
        let mut tampered = enrolment.confirm.clone();
        tampered[0] ^= 0x01;
        assert!(matches!(
            daemon.finish(&client_message, &enrolment.public_key, &tampered),
            Err(PairingError::ConfirmationFailed)
        ));
        Ok(())
    }

    #[test]
    fn a_confirmation_over_another_key_is_refused() -> TestResult {
        // The proof binds the key it enrols. Reusing a signature harvested from an earlier
        // pairing to enrol a *different* key must not work.
        let code = PairingCode::generate();
        let identity = DeviceSecretKey::generate();
        let other = DeviceSecretKey::generate();

        let (daemon, daemon_message) = DaemonPairing::begin(&code);
        let (client, client_message) = ClientPairing::begin(&code);
        let enrolment = client.finish(&daemon_message, &identity)?;

        // Valid signature, but for the client's own key rather than the one being enrolled.
        assert!(matches!(
            daemon.finish(
                &client_message,
                &other.public().to_bytes(),
                &enrolment.confirm
            ),
            Err(PairingError::ConfirmationFailed)
        ));
        Ok(())
    }

    #[test]
    fn an_exchange_can_only_be_finished_once() -> TestResult {
        // Answering a second attempt with a fresh exchange would hand an attacker another
        // guess against the same code.
        let code = PairingCode::generate();
        let identity = DeviceSecretKey::generate();
        let (daemon, daemon_message) = DaemonPairing::begin(&code);
        let (client, client_message) = ClientPairing::begin(&code);
        let enrolment = client.finish(&daemon_message, &identity)?;
        let _ = daemon.finish(&client_message, &enrolment.public_key, &enrolment.confirm)?;

        let (again, _) = ClientPairing::begin(&code);
        let second = again.finish(&daemon_message, &identity)?;
        // The daemon's state was consumed by the first finish; there is no second one to
        // call, which is why this is a type-level guarantee rather than a runtime check.
        assert_eq!(second.public_key, enrolment.public_key);
        Ok(())
    }

    #[test]
    fn a_malformed_spake2_message_is_refused() -> TestResult {
        let code = PairingCode::generate();
        let identity = DeviceSecretKey::generate();
        let (daemon, _) = DaemonPairing::begin(&code);
        // A truncated peer message must be a refusal, never a key. An all-zero element of
        // the right length is not a valid point, so it is refused too. Each attempt needs
        // its own exchange, because finishing consumes it.
        let (short, _) = ClientPairing::begin(&code);
        assert!(short.finish(&[0_u8; 3], &identity).is_err());
        let (bad_point, _) = ClientPairing::begin(&code);
        assert!(
            bad_point.finish(&[0x42_u8; 33], &identity).is_err(),
            "an invalid point must not produce a key"
        );

        assert!(matches!(
            daemon.finish(&[0_u8; 3], &[0_u8; 32], &[]),
            Err(PairingError::CodeMismatch)
        ));
        Ok(())
    }

    #[test]
    fn a_code_is_single_use_even_when_the_attempt_fails() {
        // The anti-online-guessing rule: one attempt costs one code. If a failure left the
        // code usable, 2^40 entropy would be reduced by retrying against a single code.
        let mut pending = PendingCode::new(PairingCode::generate());
        assert!(!pending.is_used());
        assert!(pending.consume().is_ok());
        assert!(pending.is_used());
        assert!(matches!(pending.consume(), Err(PairingError::AlreadyUsed)));
    }

    #[test]
    fn an_expired_code_is_refused_and_stays_refused() {
        let mut pending =
            PendingCode::with_ttl(PairingCode::generate(), std::time::Duration::from_millis(0));
        // A zero TTL is expired immediately, which is how expiry is tested without waiting
        // the real five minutes.
        assert!(pending.is_expired());
        assert!(matches!(pending.consume(), Err(PairingError::Expired)));
        // And it does not become usable again by being held.
        assert!(matches!(pending.consume(), Err(PairingError::AlreadyUsed)));
    }

    #[test]
    fn a_live_code_reports_its_remaining_time() {
        let pending =
            PendingCode::with_ttl(PairingCode::generate(), std::time::Duration::from_secs(300));
        assert!(!pending.is_expired());
        assert!(pending.remaining() <= std::time::Duration::from_secs(300));
        assert!(pending.remaining() > std::time::Duration::from_secs(290));
    }

    #[test]
    fn a_displayed_code_is_grouped_and_never_prints_its_secret() {
        let code = PairingCode::from_secret([0, 1, 2, 3, 4]);
        let shown = code.display_form();
        // Every byte becomes two symbols (one per five-bit half), so five bytes render as
        // ten symbols, grouped four at a time by separators. What matters for a human is
        // that the grouping is stable and the alphabet avoids look-alike characters.
        assert_eq!(
            shown.chars().filter(|c| *c != '-').count(),
            10,
            "got {shown:?}"
        );
        assert_eq!(shown, "0010-2030-40");
        assert!(
            !shown.contains(['I', 'L', 'O', 'U']),
            "the alphabet must avoid characters that survive transcription badly: {shown}"
        );
        // Five bytes at five bits each is more than five symbols' worth, so the renderer
        // emits two symbols per byte; what matters is that Debug leaks nothing.
        assert_eq!(format!("{code:?}"), "PairingCode(redacted)");
        assert!(!format!("{code:?}").contains(&shown));
    }

    #[test]
    fn a_generated_code_varies() {
        // Two draws colliding would be a broken RNG, not bad luck.
        let first = PairingCode::generate();
        let second = PairingCode::generate();
        assert_ne!(first.secret(), second.secret());
    }
}
