//! Self-healing against a real process.
//!
//! The unit tests in `crates/dr-dsh-daemon/src/lifecycle.rs` pin the decisions — growing delays,
//! giving up, an intentional stop not being restarted. What they cannot pin is the part that
//! touches the operating system: that a process killed the way a crash kills it is *observed*
//! as an exit, and that the daemon's answer is to start another one.
//!
//! Those two claims are the acceptance criterion ("force-kill the DSH process and the daemon
//! heals within the backoff window"), so they are checked here with a real child process and a
//! real signal.
//!
//! The stand-in is `tests/fixtures/fake-dsh.mjs` — the same fixture `supervise.rs` uses to pin
//! the readiness and authority contracts — so a kill here exercises the same startup path the
//! daemon uses in production.

use std::time::Duration;

use dr_dsh_daemon::dsh::{Supervisor, SupervisorConfig, SupervisorSpawner};
use dr_dsh_daemon::lifecycle::{Controller, Mode, Running as _, Spawner as _};

type TestResult = Result<(), Box<dyn std::error::Error>>;

/// Ports are pinned per test so a failure names the port that was taken, and two tests cannot
/// race for the same stand-in.
const PORT_CRASH: u16 = 46211;
const PORT_STOP: u16 = 46212;
/// A port of its own, not `PORT_STOP + 1`.
///
/// The wrapper script is named after the port, so two tests sharing one derive the same path
/// and one writes it while the other executes it — which the kernel refuses with "Text file
/// busy" and which looks nothing like the race that caused it. Found by a full-suite run that
/// failed once in a way five isolated runs could not reproduce.
const PORT_ATTACH: u16 = 46213;

/// Writes a wrapper that gives the fixture the port the supervisor passes as `--port`.
///
/// Named after the port so the tests in this file can run concurrently: one shared path means
/// one test truncating the script while another is executing it, which the kernel refuses with
/// `ExecutableFileBusy` and which looks nothing like the race that caused it.
fn wrapper_script(port: u16) -> Result<std::path::PathBuf, Box<dyn std::error::Error>> {
    let directory = std::env::temp_dir().join("drdshd-lifecycle-test");
    std::fs::create_dir_all(&directory)?;
    let path = directory.join(format!("fake-dsh-{port}.sh"));
    let fixture =
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/fake-dsh.mjs");
    let script = format!(
        "#!/bin/sh\n# Generated by tests/lifecycle.rs.\n\
         port=\"\"\nwhile [ $# -gt 0 ]; do\n  if [ \"$1\" = \"--port\" ]; then port=\"$2\"; shift 2; continue; fi\n  shift\ndone\n\
         exec node '{}' \"$port\"\n",
        fixture.display()
    );
    // Written to a temporary name and renamed into place, because the final path may already be
    // executing: `std::fs::write` truncates and rewrites in place, and a script being executed
    // cannot be written to — the kernel refuses with "Text file busy", a failure that names the
    // symptom and nothing about the race. A rename is atomic, so a reader sees either the old
    // file or the new one and never a half-written one.
    let temporary = path.with_extension("sh.tmp");
    std::fs::write(&temporary, script)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let mut permissions = std::fs::metadata(&temporary)?.permissions();
        permissions.set_mode(0o755);
        std::fs::set_permissions(&temporary, permissions)?;
    }
    std::fs::rename(&temporary, &path)?;
    Ok(path)
}

/// The spawner the daemon uses, pointed at the stand-in.
fn spawner(port: u16) -> Result<SupervisorSpawner, Box<dyn std::error::Error>> {
    Ok(SupervisorSpawner::new(SupervisorConfig {
        executable: wrapper_script(port)?,
        port,
    }))
}

#[tokio::test]
async fn a_killed_dsh_is_restarted_within_the_backoff_window() -> TestResult {
    // The acceptance criterion in one test: kill the process the way a crash does, and the
    // daemon brings it back without anyone asking.
    let spawner = spawner(PORT_CRASH)?;
    let mut controller = Controller::new(Mode::Managed { port: PORT_CRASH });

    controller.begin_start();
    let mut running = spawner
        .spawn()
        .await
        .map_err(|error| format!("the stand-in did not start: {error}"))?;
    controller.started(running.pid());
    assert!(
        running.pid().is_some_and(|pid| pid > 0),
        "a managed DSH has a pid"
    );
    assert_eq!(
        controller.lifecycle().state(),
        dr_dsh_proto::control::LifecycleState::Running
    );

    // Kill it the way a crash does: SIGKILL, so nothing gets a chance to shut down cleanly.
    let pid = running.pid().ok_or("no pid to kill")?;
    #[cfg(unix)]
    {
        let killed = std::process::Command::new("kill")
            .arg("-9")
            .arg(pid.to_string())
            .status()?;
        assert!(killed.success(), "the test must actually kill the process");
    }

    // The exit is observed, and the controller decides to recover.
    let how = tokio::time::timeout(Duration::from_secs(10), running.wait())
        .await
        .map_err(|_| "the daemon never noticed the process had gone")?;
    let should_restart = controller.exited(how);
    assert!(should_restart, "a crash must be restarted");

    // While recovering, a remote client sees "starting" — not "stopped" and not nothing. That
    // is what makes the UI show progress instead of looking unresponsive.
    assert_eq!(
        controller.lifecycle().state(),
        dr_dsh_proto::control::LifecycleState::Starting,
        "recovery must report as starting, got {:?}",
        controller.lifecycle()
    );
    let delay = controller.current_delay();
    assert!(
        delay <= Duration::from_secs(1),
        "the first retry is prompt: {delay:?}"
    );

    // And it really comes back: the backoff is waited out and a new process starts.
    tokio::time::sleep(delay).await;
    let mut restarted = spawner
        .spawn()
        .await
        .map_err(|error| format!("the stand-in did not restart: {error}"))?;
    controller.started(restarted.pid());
    assert_eq!(
        controller.lifecycle().state(),
        dr_dsh_proto::control::LifecycleState::Running
    );
    assert_ne!(
        restarted.pid(),
        Some(pid),
        "the restart must be a new process, not the dead one reported as alive"
    );

    restarted
        .stop()
        .await
        .map_err(|error| format!("cannot stop the restarted stand-in: {error}"))?;
    Ok(())
}

#[tokio::test]
async fn an_intentional_stop_is_not_undone_by_self_healing() -> TestResult {
    // The other half of self-healing, and the one that is easy to get wrong: a stop the
    // operator asked for must stay stopped. A daemon that treats every exit as a crash makes
    // `stop` impossible to use, and the symptom — DSH coming back a second after it was
    // stopped — looks like a bug in DSH rather than in the daemon.
    let spawner = spawner(PORT_STOP)?;
    let mut controller = Controller::new(Mode::Managed { port: PORT_STOP });

    controller.begin_start();
    let mut running = spawner
        .spawn()
        .await
        .map_err(|error| format!("the stand-in did not start: {error}"))?;
    controller.started(running.pid());

    // The operator asks for a stop, and the process is stopped the graceful way.
    controller.begin_stop();
    running
        .stop()
        .await
        .map_err(|error| format!("cannot stop the stand-in: {error}"))?;
    let how = tokio::time::timeout(Duration::from_secs(10), running.wait())
        .await
        .map_err(|_| "the stand-in ignored the stop")?;

    assert!(
        !controller.exited(how),
        "an exit the operator asked for must not be restarted"
    );
    assert_eq!(
        controller.lifecycle().state(),
        dr_dsh_proto::control::LifecycleState::Stopped
    );
    Ok(())
}

#[tokio::test]
async fn a_dsh_that_cannot_start_fails_instead_of_looping() -> TestResult {
    // A configuration mistake — here, a port that is already taken — must end in a reported
    // failure rather than an endless spawn loop. The loop would fill the process table and the
    // logs while never telling the operator what is wrong.
    let taken = std::net::TcpListener::bind("127.0.0.1:0")?;
    let port = taken.local_addr()?.port();
    let spawner = spawner(port)?;
    let mut controller = Controller::new(Mode::Managed { port });

    let mut attempts = 0_u32;
    loop {
        controller.begin_start();
        let failure = match spawner.spawn().await {
            Ok(mut running) => {
                let _ = running.stop().await;
                return Err(format!(
                    "the stand-in took port {port} while another listener held it"
                )
                .into());
            }
            Err(error) => error,
        };
        attempts += 1;
        if !controller.start_failed(failure) {
            break;
        }
        assert!(
            attempts < 10,
            "the controller must give up within its policy, not loop"
        );
    }
    assert_eq!(
        controller.lifecycle().state(),
        dr_dsh_proto::control::LifecycleState::Failed,
        "a DSH that cannot start must end as a reported failure"
    );
    match controller.lifecycle() {
        dr_dsh_daemon::lifecycle::Lifecycle::Failed { reason } => {
            assert!(
                reason.contains("gave up after"),
                "the failure must say it stopped trying: {reason}"
            );
        }
        other => return Err(format!("expected a failure, got {other:?}").into()),
    }
    Ok(())
}

#[tokio::test]
async fn attach_mode_never_touches_a_dsh_it_did_not_start() -> TestResult {
    // Criterion 5, at the level where it matters: the refusal is not merely a disabled button,
    // it is a decision this component makes. The stand-in runs, the controller is in attached
    // mode, and nothing it permits can stop that process.
    let spawner = spawner(PORT_ATTACH)?;
    let mut running: Supervisor = spawner
        .spawn()
        .await
        .map_err(|error| format!("the stand-in did not start: {error}"))?;
    let pid = running.pid().ok_or("the stand-in has no pid")?;

    let controller = Controller::new(Mode::Attached { port: PORT_ATTACH });
    assert!(
        controller
            .check_permitted(dr_dsh_proto::control::LifecycleOp::Stop)
            .is_err(),
        "attached mode must refuse a stop"
    );
    assert!(
        controller
            .check_permitted(dr_dsh_proto::control::LifecycleOp::Restart)
            .is_err(),
        "attached mode must refuse a restart"
    );
    // And the reason is a sentence a person can read, because the remote UI shows it verbatim.
    let reason = match controller.check_permitted(dr_dsh_proto::control::LifecycleOp::Stop) {
        Err(reason) => reason,
        Ok(()) => return Err("attached mode must refuse a stop".into()),
    };
    assert!(reason.contains("started outside this daemon"), "{reason}");

    // The process is genuinely still alive: a refusal that stopped it anyway would pass a test
    // that only checked the error.
    #[cfg(unix)]
    {
        let alive = std::process::Command::new("kill")
            .arg("-0")
            .arg(pid.to_string())
            .status()?;
        assert!(alive.success(), "attached mode must leave DSH running");
    }
    running
        .stop()
        .await
        .map_err(|error| format!("cannot clean up the stand-in: {error}"))?;
    Ok(())
}

/// A stand-in DSH whose lifetime the test controls.
///
/// The kill switch is a `watch` channel rather than a oneshot, because a real process has one
/// lifetime that any number of `wait` calls observe. A oneshot that a handle *invents* per call
/// makes `wait` return immediately on the second call, which is how a broken stand-in makes a
/// restart test pass without a restart ever happening.
struct FakeHandle {
    pid: u32,
    deaths: tokio::sync::watch::Receiver<bool>,
    stopped: std::sync::Arc<std::sync::atomic::AtomicBool>,
}

#[async_trait::async_trait]
impl dr_dsh_daemon::lifecycle::Running for FakeHandle {
    fn pid(&self) -> Option<u32> {
        Some(self.pid)
    }

    async fn wait(&mut self) -> String {
        loop {
            if *self.deaths.borrow() {
                return "DSH exited: killed by signal 9".to_owned();
            }
            if self.deaths.changed().await.is_err() {
                return "DSH exited: the stand-in closed".to_owned();
            }
        }
    }

    async fn stop(&mut self) -> Result<(), String> {
        self.stopped
            .store(true, std::sync::atomic::Ordering::SeqCst);
        Ok(())
    }
}

/// Spawns stand-ins and hands out a kill switch per process.
#[derive(Default)]
struct FakeSpawner {
    kills: std::sync::Mutex<Vec<tokio::sync::watch::Sender<bool>>>,
    stopped: std::sync::Arc<std::sync::atomic::AtomicBool>,
    spawned: std::sync::atomic::AtomicU32,
    /// Set to make every spawn fail, for the "cannot start" path.
    fail: bool,
}

impl FakeSpawner {
    /// Kills the most recently spawned stand-in, as a crash would.
    fn kill_latest(&self) -> Result<(), Box<dyn std::error::Error>> {
        let switch = self
            .kills
            .lock()
            .map_err(|_| "poisoned")?
            .pop()
            .ok_or("no kill switch")?;
        let _ = switch.send(true);
        Ok(())
    }
}

#[async_trait::async_trait]
impl dr_dsh_daemon::lifecycle::Spawner for FakeSpawner {
    type Handle = FakeHandle;

    async fn spawn(&self) -> Result<Self::Handle, String> {
        if self.fail {
            return Err("the port is in use".to_owned());
        }
        let pid = self
            .spawned
            .fetch_add(1, std::sync::atomic::Ordering::SeqCst)
            + 100;
        let (deaths, receiver) = tokio::sync::watch::channel(false);
        self.kills
            .lock()
            .map_err(|_| "poisoned".to_owned())?
            .push(deaths);
        Ok(FakeHandle {
            pid,
            deaths: receiver,
            stopped: std::sync::Arc::clone(&self.stopped),
        })
    }
}

/// Adapts an `Arc<Spawner>` to the `'static` bound the driver needs.
///
/// The driver takes its spawner by value so the task can own it; sharing one across assertions
/// is what lets a test read the spawn count the driver produced.
struct SharedSpawner(std::sync::Arc<FakeSpawner>);

#[async_trait::async_trait]
impl dr_dsh_daemon::lifecycle::Spawner for SharedSpawner {
    type Handle = FakeHandle;

    async fn spawn(&self) -> Result<Self::Handle, String> {
        self.0.spawn().await
    }
}

/// Waits until the published state satisfies a predicate.
async fn wait_for_state(
    handle: &dr_dsh_daemon::lifecycle::Handle,
    predicate: impl Fn(&dr_dsh_daemon::lifecycle::Lifecycle) -> bool,
) -> Result<(), Box<dyn std::error::Error>> {
    for _ in 0..200 {
        if predicate(&handle.snapshot()) {
            return Ok(());
        }
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    Err(format!("the state never arrived; it is {:?}", handle.snapshot()).into())
}

#[tokio::test]
async fn the_driver_restarts_a_process_that_dies() -> TestResult {
    // The driver is what runs in the shipped daemon. The tests above prove the *decisions* are
    // right against a real process; this proves the decisions are actually wired to one, which
    // is a different claim — a driver that never restarts would pass every test above.
    let (handle, driver) = dr_dsh_daemon::lifecycle::channel(
        Mode::Managed { port: 3080 },
        dr_dsh_daemon::lifecycle::RestartPolicy {
            base: Duration::from_millis(20),
            max: Duration::from_millis(50),
            max_attempts: 5,
        },
    );
    let spawner = std::sync::Arc::new(FakeSpawner::default());
    let task = tokio::spawn(driver.run(SharedSpawner(std::sync::Arc::clone(&spawner))));

    // It starts on its own: a daemon that came up with nothing running and no attempt scheduled
    // would report a DSH that never arrives.
    wait_for_state(&handle, |state| {
        matches!(state, dr_dsh_daemon::lifecycle::Lifecycle::Running { .. })
    })
    .await?;
    assert_eq!(spawner.spawned.load(std::sync::atomic::Ordering::SeqCst), 1);
    let first_pid = match handle.snapshot() {
        dr_dsh_daemon::lifecycle::Lifecycle::Running { pid } => pid.ok_or("no pid")?,
        other => return Err(format!("expected a running DSH, got {other:?}").into()),
    };

    // Kill it the way a crash does, and the driver brings it back. The wait is for a *different*
    // pid rather than merely for "running": the published state is still the old process's
    // until the driver notices the death, so waiting on the state alone would pass immediately
    // and assert nothing.
    spawner.kill_latest()?;
    wait_for_state(&handle, |state| {
        matches!(state, dr_dsh_daemon::lifecycle::Lifecycle::Running { pid: Some(pid) } if *pid != first_pid)
    })
    .await?;
    assert_eq!(
        spawner.spawned.load(std::sync::atomic::Ordering::SeqCst),
        2,
        "a restart must be a new process, not the dead one reported as alive"
    );

    task.abort();
    Ok(())
}

#[tokio::test]
async fn an_adopted_process_that_dies_is_restarted() -> TestResult {
    // The daemon starts DSH before it has a driver, because it needs the readiness line for its
    // own startup checks, and then hands the process over. Adopting has to assert that DSH is
    // *meant* to be running: the first version did not, so the first crash was classified as an
    // exit the operator asked for and the driver left DSH down — self-healing that never
    // healed, and nothing in the logs to say so. Found by killing a real DSH.
    let (handle, driver) = dr_dsh_daemon::lifecycle::channel(
        Mode::Managed { port: 3080 },
        dr_dsh_daemon::lifecycle::RestartPolicy {
            base: Duration::from_millis(20),
            max: Duration::from_millis(50),
            max_attempts: 5,
        },
    );
    let spawner = std::sync::Arc::new(FakeSpawner::default());
    // The process the daemon already started, adopted before the driver runs.
    let adopted = spawner.spawn().await.map_err(|error| error.to_string())?;
    let adopted_pid = adopted.pid().ok_or("the adopted process has no pid")?;
    let task = tokio::spawn(
        driver
            .adopt(Box::new(adopted))
            .run(SharedSpawner(std::sync::Arc::clone(&spawner))),
    );
    // The adopted process is the one being watched, so nothing new is started yet.
    wait_for_state(&handle, |state| {
        matches!(state, dr_dsh_daemon::lifecycle::Lifecycle::Running { .. })
    })
    .await?;
    assert_eq!(
        spawner.spawned.load(std::sync::atomic::Ordering::SeqCst),
        1,
        "adopting must not spawn a second DSH"
    );

    // Kill the adopted process: it must come back.
    spawner.kill_latest()?;
    wait_for_state(&handle, |state| {
        matches!(state, dr_dsh_daemon::lifecycle::Lifecycle::Running { pid: Some(pid) } if *pid != adopted_pid)
    })
    .await?;
    assert_eq!(
        spawner.spawned.load(std::sync::atomic::Ordering::SeqCst),
        2,
        "an adopted process that dies must be replaced"
    );

    task.abort();
    Ok(())
}

#[tokio::test]
async fn an_attach_mode_driver_never_permitted_a_command() -> TestResult {
    // The refusal reached through the driver, which is the path the control plane takes.
    let (handle, driver) = dr_dsh_daemon::lifecycle::channel(
        Mode::Attached { port: 3080 },
        dr_dsh_daemon::lifecycle::RestartPolicy::default(),
    );
    let spawner = std::sync::Arc::new(FakeSpawner::default());
    let task = tokio::spawn(driver.run(SharedSpawner(std::sync::Arc::clone(&spawner))));

    let result = handle
        .command(dr_dsh_proto::control::LifecycleOp::Stop)
        .await;
    assert!(!result.ok, "a stop must be refused in attach mode");
    assert!(
        result
            .error
            .as_deref()
            .is_some_and(|reason| reason.contains("started outside this daemon")),
        "the refusal must explain itself: {:?}",
        result.error
    );
    assert_eq!(
        spawner.spawned.load(std::sync::atomic::Ordering::SeqCst),
        0,
        "attach mode must not start a DSH of its own"
    );
    task.abort();
    Ok(())
}

#[tokio::test]
async fn a_restart_command_replaces_the_process() -> TestResult {
    let (handle, driver) = dr_dsh_daemon::lifecycle::channel(
        Mode::Managed { port: 3080 },
        dr_dsh_daemon::lifecycle::RestartPolicy {
            base: Duration::from_millis(20),
            max: Duration::from_millis(50),
            max_attempts: 5,
        },
    );
    let spawner = std::sync::Arc::new(FakeSpawner::default());
    let task = tokio::spawn(driver.run(SharedSpawner(std::sync::Arc::clone(&spawner))));
    wait_for_state(&handle, |state| {
        matches!(state, dr_dsh_daemon::lifecycle::Lifecycle::Running { .. })
    })
    .await?;

    let result = handle
        .command(dr_dsh_proto::control::LifecycleOp::Restart)
        .await;
    assert!(result.ok, "the restart must succeed: {:?}", result.error);
    assert_eq!(result.state, dr_dsh_proto::control::LifecycleState::Running);
    assert_eq!(
        spawner.spawned.load(std::sync::atomic::Ordering::SeqCst),
        2,
        "a restart is a stop followed by a start"
    );
    task.abort();
    Ok(())
}
