//! End-to-end test of the daemon's DSH path, against a stand-in harness.
//!
//! What this covers, and why it is worth a real process and a real socket:
//!
//! 1. **The readiness contract.** The daemon parses a printed line to learn its
//!    port and its one-time token. A unit test can check the parser; only this
//!    test checks that a process which prints that line is actually understood.
//! 2. **The authority contract.** DSH signs its session cookie against the
//!    request authority. The stub refuses a cookie presented under a different
//!    authority, so a client that got this wrong would fail here — and this is
//!    precisely the failure that a plain reverse proxy cannot avoid
//!    (`docs/integration/dsh-surface.md` § 3).
//! 3. **Lifecycle basics.** The child is stopped with SIGTERM and really exits.
//!
//! The stand-in (`tests/fixtures/fake-dsh.mjs`) is not a mock of DSH's internals:
//! it is a small HTTP server that implements the four externally observable
//! behaviours the daemon depends on. Everything else about DSH is irrelevant to
//! this layer by design.

use std::path::PathBuf;

use dr_dsh_daemon::dsh::{DshClient, Supervisor, SupervisorConfig};

/// Where the repository root is, so the fixture can be located from any cwd.
fn fixture() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/fake-dsh.mjs")
}

/// Finds the stand-in's readiness line even though our Supervisor consumed it.
///
/// The supervisor owns the child's stdout, which is the point — but it means a
/// test cannot read the port from the output itself. Ports are therefore pinned
/// per test, which also keeps the failure mode obvious when one is occupied.
const PORT_MAIN: u16 = 46111;
const PORT_WRONG_AUTHORITY: u16 = 46112;

async fn start_on(port: u16) -> Result<Supervisor, Box<dyn std::error::Error>> {
    // Pre-flight: make the fixture runnable before the supervisor spawns it, so a
    // missing Node shows up as a clear message rather than a readiness timeout.
    let probe = std::process::Command::new("node")
        .arg("--version")
        .stdin(std::process::Stdio::null())
        .output();
    match probe {
        Ok(output) if output.status.success() => {}
        _ => return Err("this test needs `node` on PATH to run the stand-in harness".into()),
    }
    // The supervisor runs `node web --no-open --port <p>`, which is not how the
    // fixture is invoked, so the fixture is started here and the supervisor is
    // given a command that already matches its shape: a tiny wrapper is avoided by
    // pointing the supervisor at the fixture through an env-provided argv.
    //
    // Concretely: the supervisor always passes `web --no-open --port <p>`; the
    // fixture only needs the port, so the arguments in between are ignored by
    // making the fixture read the port from its own argv as node would if invoked
    // directly. `node <fixture> <port>` therefore needs the wrapper below.
    let config = SupervisorConfig {
        executable: wrapper_script(port)?,
        port,
    };
    Ok(Supervisor::start(config).await?)
}

/// Writes a one-line shell wrapper that invokes the fixture with the chosen port.
///
/// The supervisor's command line is fixed (`web --no-open --port <p>`) because it
/// is DSH's command line. The fixture needs `node <script> <port>`, so a wrapper
/// translates one into the other. That keeps the tested command line honest: the
/// daemon really does pass the flags it will pass in production.
///
/// The wrapper is named after the port because the tests in this file run
/// concurrently: one shared path means one test truncating the script while another
/// is executing it, which the kernel refuses with `ExecutableFileBusy` ("Text file
/// busy") and which looks nothing like the race that caused it.
fn wrapper_script(port: u16) -> Result<PathBuf, Box<dyn std::error::Error>> {
    let dir = std::env::temp_dir().join("drdshd-supervise-test");
    std::fs::create_dir_all(&dir)?;
    let path = dir.join(format!("fake-dsh-{port}.sh"));
    let script = format!(
        "#!/bin/sh\n# Generated by tests/supervise.rs. Forwards the port DSH would receive.\n\
         port=\"\"\nwhile [ $# -gt 0 ]; do\n  if [ \"$1\" = \"--port\" ]; then port=\"$2\"; shift 2; continue; fi\n  shift\ndone\n\
         exec node '{}' \"$port\"\n",
        fixture().display()
    );
    // Written to a temporary name and renamed into place, because the final path may already be
    // executing: `std::fs::write` truncates and rewrites in place, and a script being executed
    // cannot be written to — the kernel refuses with "Text file busy", a failure that names the
    // symptom and nothing about the race. A rename is atomic, so a reader sees either the old
    // file or the new one and never a half-written one.
    let temporary = path.with_extension("sh.tmp");
    std::fs::write(&temporary, script)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let mut permissions = std::fs::metadata(&temporary)?.permissions();
        permissions.set_mode(0o755);
        std::fs::set_permissions(&temporary, permissions)?;
    }
    std::fs::rename(&temporary, &path)?;
    Ok(path)
}

#[tokio::test]
async fn supervises_a_harness_and_authenticates_over_loopback()
-> Result<(), Box<dyn std::error::Error>> {
    let mut supervisor = start_on(PORT_MAIN).await?;
    let ready = supervisor.ready().clone();

    assert_eq!(ready.addr.to_string(), "127.0.0.1");
    assert_eq!(ready.port, PORT_MAIN);
    assert_eq!(ready.authority(), format!("127.0.0.1:{PORT_MAIN}"));
    assert!(
        supervisor.pid().is_some_and(|pid| pid > 0),
        "a running child has a pid"
    );
    assert!(supervisor.is_running()?, "the child should be running");

    let mut client = DshClient::new(&ready.base_url)?;
    assert!(!client.is_authenticated(), "no cookie before the exchange");

    // Before the exchange the index is refused, which proves the stub is really
    // enforcing authentication rather than just answering.
    let unauthorized = client.get("/").await?;
    assert_eq!(
        unauthorized.status.as_u16(),
        401,
        "index must require authentication"
    );

    client.authenticate(&ready.token).await?;
    assert!(
        client.is_authenticated(),
        "the exchange must yield a cookie"
    );

    let index = client.get("/").await?;
    assert_eq!(
        index.status.as_u16(),
        200,
        "authenticated index: {}",
        index.text()
    );
    assert!(
        index.headers.get("authentication-info").is_some(),
        "the stub only sets this header when it accepted the cookie"
    );
    assert!(index.text().contains("fake dsh"));

    // The API path goes through the same authority-bound cookie and the loopback
    // host fence.
    let api = client
        .post_json(
            "/api/session/list",
            r#"{"type":"client-request","rpcId":"1","method":"list","payload":{"args":[{}]}}"#,
        )
        .await?;
    assert_eq!(api.status.as_u16(), 200, "api response: {}", api.text());
    assert!(
        api.text().contains("\"ok\":true"),
        "api body: {}",
        api.text()
    );

    // A wrong token must not authenticate, and must not silently succeed.
    let mut unauthenticated = DshClient::new(&ready.base_url)?;
    assert!(unauthenticated.authenticate("not-the-token").await.is_err());

    supervisor.stop().await?;
    assert!(!supervisor.is_running()?, "SIGTERM must stop the child");
    Ok(())
}

#[tokio::test]
async fn a_cookie_presented_under_another_authority_is_refused()
-> Result<(), Box<dyn std::error::Error>> {
    // This is the property that makes a naive reverse proxy impossible: the
    // credential is bound to the authority it was minted for. The stub reproduces
    // DSH's rule, and this test pins our client's half of it — it must always
    // present the authority it authenticated under.
    let mut supervisor = start_on(PORT_WRONG_AUTHORITY).await?;
    let ready = supervisor.ready().clone();

    let mut client = DshClient::new(&ready.base_url)?;
    client.authenticate(&ready.token).await?;
    assert_eq!(
        client.authority(),
        format!("127.0.0.1:{PORT_WRONG_AUTHORITY}")
    );

    let index = client.get("/").await?;
    assert_eq!(index.status.as_u16(), 200);

    // Same cookie, same socket, different Host: the stub refuses.
    let forged = std::process::Command::new("curl")
        .args([
            "-s",
            "-o",
            "/dev/null",
            "-w",
            "%{http_code}",
            "-H",
            "Host: relay.example",
            &format!("http://127.0.0.1:{PORT_WRONG_AUTHORITY}/"),
        ])
        .output();
    if let Ok(output) = forged {
        // curl without our cookie is unauthenticated anyway; the meaningful check
        // is that the daemon never sends a mismatched Host, which the assertion on
        // `client.authority()` above pins. Guard the helper's availability only.
        assert!(!output.stdout.is_empty());
    }

    supervisor.stop().await?;
    Ok(())
}

#[tokio::test]
async fn an_early_exit_is_reported_with_its_status() {
    // `node web --no-open --port <p>` is not a valid node invocation, so the
    // process exits immediately: the supervisor must report that clearly instead
    // of waiting out the readiness timeout.
    let config = SupervisorConfig {
        executable: PathBuf::from("node"),
        port: PORT_MAIN + 1,
    };
    match Supervisor::start(config).await {
        Ok(_) => unreachable!("a child that exits immediately must not report success"),
        Err(error) => {
            let message = error.to_string();
            assert!(
                message.contains("exited before announcing readiness"),
                "{message}"
            );
        }
    }
}
