//! Where the room key comes from.
//!
//! ADR-0013 decided this, and the reason is a failure mode rather than convenience: `drdshd run` and
//! `drdshd pair` each used to require `--room-key`, and giving them *different* keys produced a device
//! that could never connect — the symptom is `no daemon is serving this room`, which names neither the
//! key nor the command that got it wrong. Now both commands read the same file by default:
//!
//! ```text
//! order:  --room-key  >  $DSHD_STATE_DIR/room-key  >  generate one and write it there (0600)
//! ```
//!
//! ## What this module will not do
//!
//! * **It will not print the key.** Pairing is what hands the key to a device, and a key printed once
//!   "for convenience" lives on in terminal scrollback, in `journalctl`, and in pasted bug reports.
//!   The path is printed instead — that is what an operator needs in order to back it up or remove it.
//! * **It will not write a key given on the command line.** `--room-key` means "use this one now", not
//!   "make this the default": a command line is a leak path (shell history, `ps`, a systemd `Environment=`
//!   line), so it must not become the stored value behind the operator's back.
//! * **It will not replace a key it cannot read.** A truncated or corrupt `room-key` file fails with the
//!   path in the message. Regenerating would silently invalidate every paired device — the same reason
//!   the device registry fails closed rather than degrading to an empty table.

use std::path::{Path, PathBuf};

/// File name inside the daemon's state directory.
pub const FILE_NAME: &str = "room-key";

/// Where the key that is in use came from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Source {
    /// `--room-key` on this command line.
    CommandLine,
    /// The state directory's file.
    File(PathBuf),
    /// Generated by this run and written to the state directory.
    Generated(PathBuf),
}

/// A resolved room key, with what to tell the operator about it.
#[derive(Clone)]
pub struct Resolved {
    /// The key itself. Never printed, never logged.
    pub root: [u8; dr_dsh_crypto::SESSION_KEY_LEN],
    /// Where it came from.
    pub source: Source,
    /// A stored key that disagrees with the command line, when there is one.
    ///
    /// Reported rather than resolved. The command line wins for this run — that is what an explicit
    /// flag means — but a daemon that quietly ignored the difference would make "two sources" the
    /// silent configuration error the ADR exists to remove.
    pub conflicts_with: Option<PathBuf>,
}

impl core::fmt::Debug for Resolved {
    /// Prints the source, never the key.
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter
            .debug_struct("Resolved")
            .field("root", &"<redacted>")
            .field("source", &self.source)
            .field("conflicts_with", &self.conflicts_with)
            .finish()
    }
}

impl Resolved {
    /// The lines an operator sees, so `run` and `pair` cannot describe the same fact differently.
    #[must_use]
    pub fn announcement(&self) -> Vec<String> {
        let mut lines = match &self.source {
            Source::CommandLine => vec![
                "room key: from the command line (not written to the state directory)".to_owned(),
            ],
            Source::File(path) => vec![format!("room key: {}", path.display())],
            Source::Generated(path) => vec![
                format!("room key: generated and stored at {}", path.display()),
                "          it is what your paired devices were given; back it up with the state \
                 directory, and do not delete it"
                    .to_owned(),
            ],
        };
        if let Some(path) = &self.conflicts_with {
            lines.push(format!(
                "room key: NOTE — the stored key at {} is different, and was not changed. This run \
                 uses the command-line one, so a device paired with the stored key will not reach \
                 this daemon until you use it again.",
                path.display()
            ));
        }
        lines
    }
}

/// The room key file inside a state directory.
#[must_use]
pub fn path_in(directory: &Path) -> PathBuf {
    directory.join(FILE_NAME)
}

/// Resolves the room key for a command that serves a room.
///
/// # Errors
///
/// Returns an error when the stored key cannot be read or is not a room key. It never regenerates over
/// an existing file, and never writes a key that came from the command line.
pub fn resolve(directory: &Path, from_command_line: Option<&str>) -> anyhow::Result<Resolved> {
    use anyhow::Context as _;

    let path = path_in(directory);
    let stored = read_stored(&path)?;

    match (from_command_line, stored) {
        (Some(encoded), stored) => {
            let root = crate::decode_room_key(encoded)?;
            // Compared without early exit, because the *result* is the fact being reported.
            let conflicts_with = match stored {
                Some(existing) if existing != root => Some(path),
                _ => None,
            };
            Ok(Resolved {
                root,
                source: Source::CommandLine,
                conflicts_with,
            })
        }
        (None, Some(root)) => Ok(Resolved {
            root,
            source: Source::File(path),
            conflicts_with: None,
        }),
        (None, None) => {
            let root = dr_dsh_crypto::connection_salt();
            write_private(&path, &encode(&root))
                .with_context(|| format!("cannot write the room key to {}", path.display()))?;
            Ok(Resolved {
                root,
                source: Source::Generated(path),
                conflicts_with: None,
            })
        }
    }
}

/// Reads the stored key, if there is one.
///
/// # Errors
///
/// Returns an error when a file exists but is not a usable room key. The message names the path and
/// says what to do, because the one thing a caller must not do here is guess.
fn read_stored(path: &Path) -> anyhow::Result<Option<[u8; dr_dsh_crypto::SESSION_KEY_LEN]>> {
    use anyhow::Context as _;

    let text = match std::fs::read_to_string(path) {
        Ok(text) => text,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(error)
                .with_context(|| format!("cannot read the room key at {}", path.display()));
        }
    };
    let encoded = text.trim();
    if encoded.is_empty() {
        anyhow::bail!(
            "the room key file {} is empty. Delete it to have a new key generated, but note that \
             every device paired with the old key must be paired again",
            path.display()
        );
    }
    // The decode error is *inside* the message rather than attached as context: a truncated key's
    // useful sentence is "must be 32 bytes … got 3 bytes", and `anyhow`'s context would hide it behind
    // the sentence about the file when a caller prints the error.
    let root = crate::decode_room_key(encoded).map_err(|error| {
        anyhow::anyhow!(
            "the room key file {} is not a room key: {error}. Delete it to have a new one generated, \
             but note that every device paired with the old key must be paired again",
            path.display()
        )
    })?;
    Ok(Some(root))
}

/// Encodes a key the way `--room-key` accepts it and the file stores it.
#[must_use]
pub fn encode(root: &[u8; dr_dsh_crypto::SESSION_KEY_LEN]) -> String {
    use base64::Engine as _;
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(root)
}

/// Writes a file only its owner can read.
///
/// Created with the mode rather than chmod-ed afterwards: a key that exists for a moment with wider
/// permissions has been readable for a moment, and on a shared machine that is enough.
fn write_private(path: &Path, contents: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    use std::io::Write as _;

    // `create_new` rather than `create`: this function must never be the one that overwrites a key
    // somebody's paired devices depend on, and the flag makes that a property of the syscall instead
    // of a promise in a comment.
    #[cfg(unix)]
    let mut file = {
        use std::os::unix::fs::OpenOptionsExt as _;
        std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(path)?
    };
    #[cfg(not(unix))]
    let mut file = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)?;

    file.write_all(contents.as_bytes())?;
    file.write_all(b"\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    type TestResult = Result<(), Box<dyn std::error::Error>>;

    fn key(byte: u8) -> [u8; dr_dsh_crypto::SESSION_KEY_LEN] {
        [byte; dr_dsh_crypto::SESSION_KEY_LEN]
    }

    #[test]
    fn a_first_run_generates_a_key_and_stores_it_privately() -> TestResult {
        let directory = tempfile::tempdir()?;
        let resolved = resolve(directory.path(), None)?;
        let Source::Generated(path) = &resolved.source else {
            return Err(format!("expected a generated key, got {:?}", resolved.source).into());
        };
        let stored = std::fs::read_to_string(path)?;
        assert_eq!(stored.trim(), encode(&resolved.root));

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt as _;
            let mode = std::fs::metadata(path)?.permissions().mode();
            assert_eq!(mode & 0o777, 0o600, "mode {mode:o}");
        }

        // And the next command gets the same key, which is the whole point: `run` and `pair` cannot
        // disagree any more.
        let second = resolve(directory.path(), None)?;
        assert_eq!(second.root, resolved.root);
        assert!(matches!(second.source, Source::File(_)));
        Ok(())
    }

    #[test]
    fn a_command_line_key_is_used_and_not_stored() -> TestResult {
        let directory = tempfile::tempdir()?;
        let encoded = encode(&key(7));
        let resolved = resolve(directory.path(), Some(&encoded))?;
        assert_eq!(resolved.root, key(7));
        assert_eq!(resolved.source, Source::CommandLine);
        assert_eq!(resolved.conflicts_with, None);
        assert!(
            !path_in(directory.path()).exists(),
            "a key from the command line must not become the stored one"
        );
        Ok(())
    }

    #[test]
    fn a_command_line_key_that_disagrees_with_the_file_is_reported() -> TestResult {
        let directory = tempfile::tempdir()?;
        let generated = resolve(directory.path(), None)?;
        let other = encode(&key(9));
        let resolved = resolve(directory.path(), Some(&other))?;
        assert_eq!(resolved.root, key(9), "the explicit flag wins for this run");
        assert_eq!(resolved.conflicts_with, Some(path_in(directory.path())));
        // The stored key is left alone: rewriting it would silently unpair every device.
        assert_eq!(
            std::fs::read_to_string(path_in(directory.path()))?.trim(),
            encode(&generated.root)
        );
        let announcement = resolved.announcement().join("\n");
        assert!(announcement.contains("different"), "{announcement}");
        Ok(())
    }

    #[test]
    fn the_same_key_from_both_sources_is_not_a_conflict() -> TestResult {
        let directory = tempfile::tempdir()?;
        let generated = resolve(directory.path(), None)?;
        let resolved = resolve(directory.path(), Some(&encode(&generated.root)))?;
        assert_eq!(resolved.conflicts_with, None);
        Ok(())
    }

    #[test]
    fn a_key_that_cannot_be_read_fails_instead_of_being_replaced() -> TestResult {
        let directory = tempfile::tempdir()?;
        let path = path_in(directory.path());
        std::fs::write(&path, "not a key\n")?;
        let error = match resolve(directory.path(), None) {
            Ok(resolved) => {
                return Err(format!("a corrupt key was accepted: {:?}", resolved.source).into());
            }
            Err(error) => error.to_string(),
        };
        assert!(error.contains("not a room key"), "{error}");
        assert!(
            error.contains(&path.display().to_string()),
            "the message has to name the file: {error}"
        );
        assert!(
            error.contains("must be paired again"),
            "and say what replacing it would cost: {error}"
        );
        assert_eq!(
            std::fs::read_to_string(&path)?,
            "not a key\n",
            "the file is left exactly as it was"
        );
        Ok(())
    }

    #[test]
    fn a_truncated_key_is_refused_with_the_length_in_the_message() -> TestResult {
        let directory = tempfile::tempdir()?;
        std::fs::write(path_in(directory.path()), "AAAA\n")?;
        let message = resolve(directory.path(), None)
            .map(|_| String::new())
            .unwrap_or_else(|error| error.to_string());
        // Both halves matter: *that* it is refused, and *why* — a message that only said "not a room
        // key" would leave an operator guessing whether the file is truncated or was never valid.
        assert!(message.contains("32 bytes"), "{message}");
        assert!(message.contains("got 3 bytes"), "{message}");
        Ok(())
    }

    #[test]
    fn an_empty_file_says_so_rather_than_looking_like_a_missing_one() -> TestResult {
        let directory = tempfile::tempdir()?;
        std::fs::write(path_in(directory.path()), "\n")?;
        let message = resolve(directory.path(), None)
            .map(|_| String::new())
            .unwrap_or_else(|error| error.to_string());
        assert!(message.contains("is empty"), "{message}");
        Ok(())
    }

    #[test]
    fn the_announcement_never_contains_the_key() -> TestResult {
        let directory = tempfile::tempdir()?;
        let resolved = resolve(directory.path(), None)?;
        let rendered = format!("{:?}\n{}", resolved, resolved.announcement().join("\n"));
        assert!(
            !rendered.contains(&encode(&resolved.root)),
            "the key must not appear anywhere a person or a log can read it: {rendered}"
        );
        Ok(())
    }

    #[test]
    fn a_key_on_the_command_line_can_be_encoded_and_read_back() -> TestResult {
        let directory = tempfile::tempdir()?;
        let root = key(3);
        let resolved = resolve(directory.path(), Some(&encode(&root)))?;
        assert_eq!(resolved.root, root);
        assert_eq!(encode(&resolved.root), encode(&root));
        Ok(())
    }
}
