/**
 * The Ed25519 group, in `BigInt` — the arithmetic the pairing PAKE needs and WebCrypto
 * does not expose.
 *
 * ## Why this file exists
 *
 * Pairing runs SPAKE2, and SPAKE2 needs three things from a group: scalar multiplication
 * of the generator, multiplication of two *fixed* public points by a password-derived
 * scalar, and addition of the results. WebCrypto offers exactly one of them, and only for
 * Diffie-Hellman on other curves: there is no API that adds two points, and none that
 * multiplies an arbitrary point by an arbitrary scalar on Ed25519.
 *
 * The alternatives were worse, and both are recorded in `docs/security.md`:
 *
 * * Compiling the daemon's `spake2` crate to WebAssembly would keep one implementation,
 *   but it puts a compiled binary in the client bundle and requires the relay to widen its
 *   content-security policy for `wasm-unsafe-eval` — a policy that exists precisely because
 *   this page handles keys.
 * * A reduced browser-only pairing protocol would mean two protocols with different
 *   security properties, which is what `crates/dr-dsh-crypto/src/pairing.rs` refuses on
 *   purpose.
 *
 * So the construction stays identical and only the arithmetic is re-expressed. It is pinned
 * by vectors generated by the Rust implementation
 * (`packages/crypto/conformance/pairing-vectors.json`, written by
 * `crates/dr-dsh-crypto/tests/pairing_vectors.rs`) and by a real exchange against a real
 * daemon.
 *
 * ## Why this file lives in the PWA rather than in `packages/crypto`
 *
 * The relay serves client modules as *flat* files (`/client/<name>.js`; see
 * `crates/dr-dsh-relay/src/assets.rs`), and a browser cannot resolve a bare specifier such as
 * `@dr.dsh/crypto` without a bundler or an import map — and an import map is an inline
 * script, which the shell's content-security policy forbids for good reason. Client code the
 * browser has to load therefore lives here, and `packages/crypto` keeps what runs in Node:
 * the shared labels and shapes. It is the same constraint that made `tunnel.ts`
 * self-contained. The corpus stays in `packages/crypto/conformance/` because it belongs to
 * the crypto layer, not to one client.
 *
 * ## What this file is not
 *
 * It is not constant-time, and it does not pretend to be: `BigInt` has no fixed-time
 * operations, so the scalar multiplication below leaks its scalar to anyone who can measure
 * this process's execution. That is stated rather than hidden. The daemon keeps using
 * `curve25519-dalek`, which is the side that holds the device registry, and the value this
 * leaks on the client is a single-use pairing code that expires in five minutes and is on
 * the screen of the person running the exchange. Local timing attacks against one's own
 * browser are outside the threat model; `docs/security.md` § 3.2 says what the auditor
 * should check instead.
 *
 * The formulas are the standard ones for the twisted Edwards curve `-x² + y² = 1 + d·x²·y²`
 * in extended coordinates (Hisil–Wong–Carter–Dawson, "Twisted Edwards Curves Revisited",
 * add-2008-hwcd-3). They are complete for `a = -1`, so no addition has an exceptional case
 * and a plain double-and-add ladder is correct for every input.
 *
 * @module
 */

/** The field prime, 2²⁵⁵ − 19. */
const P = (1n << 255n) - 19n;

/**
 * The order of the prime-order subgroup, 2²⁵² + 27742317777372353535851937790883648493.
 *
 * Scalars are reduced modulo this, matching `curve25519_dalek::Scalar`: a scalar that is
 * merely "a 256-bit number" produces a different point than the Rust side computes.
 */
const ORDER = (1n << 252n) + 27742317777372353535851937790883648493n;

/** The curve constant `d = -121665/121666`. */
const D = mod(-121665n * inverse(121666n));

/** A square root of −1, used by the decompression step. */
const SQRT_M1 = power(2n, (P - 1n) / 4n);

/** Two times `d`, precomputed because every point addition uses it. */
const D2 = mod(2n * D);

/**
 * The Ed25519 base point, in its standard compressed encoding.
 *
 * `y = 4/5` with an even `x`; decompressed below rather than written out as coordinates, so
 * that the decompression path is exercised by every exchange instead of only by a test.
 */
const BASE_COMPRESSED = hexToBytes(
  '5866666666666666666666666666666666666666666666666666666666666666',
);

/** Why a byte string is not a point. */
export class Ed25519Error extends Error {
  public constructor(message: string) {
    super(message);
    this.name = 'Ed25519Error';
  }
}

/** A curve point in extended coordinates: `x = X/Z`, `y = Y/Z`, `T = XY/Z`. */
export interface EdwardsPoint {
  /** `X`. */
  readonly x: bigint;
  /** `Y`. */
  readonly y: bigint;
  /** `Z`. */
  readonly z: bigint;
  /** `T`. */
  readonly t: bigint;
}

/** The neutral element, in extended coordinates. */
export const IDENTITY: EdwardsPoint = { x: 0n, y: 1n, z: 1n, t: 0n };

/** The generator of the prime-order subgroup. */
export const BASE_POINT: EdwardsPoint = decompressPoint(BASE_COMPRESSED);

/** Reduces a field element into `[0, p)`. */
function mod(value: bigint): bigint {
  const reduced = value % P;
  return reduced < 0n ? reduced + P : reduced;
}

/** Modular exponentiation by square-and-multiply. */
function power(base: bigint, exponent: bigint): bigint {
  let result = 1n;
  let square = mod(base);
  let remaining = exponent;
  while (remaining > 0n) {
    if ((remaining & 1n) === 1n) result = (result * square) % P;
    square = (square * square) % P;
    remaining >>= 1n;
  }
  return result;
}

/** Modular inverse, by Fermat's little theorem. */
function inverse(value: bigint): bigint {
  return power(value, P - 2n);
}

/**
 * Adds two points.
 *
 * The unified formula: it is correct for `P + Q`, for `P + P`, and for the neutral element,
 * with no branch. That completeness is what allows the ladder below to be a loop with one
 * addition per bit instead of a case analysis that has to be right for every input.
 *
 * @param left - first point.
 * @param right - second point.
 */
export function addPoints(left: EdwardsPoint, right: EdwardsPoint): EdwardsPoint {
  const a = ((left.y - left.x) * (right.y - right.x)) % P;
  const b = ((left.y + left.x) * (right.y + right.x)) % P;
  const c = left.t * D2 * right.t % P;
  const d = left.z * 2n * right.z % P;
  const e = b - a;
  const f = d - c;
  const g = d + c;
  const h = b + a;
  return {
    x: mod(e * f),
    y: mod(g * h),
    t: mod(e * h),
    z: mod(f * g),
  };
}

/**
 * Negates a point.
 *
 * @param point - the point to negate.
 */
export function negatePoint(point: EdwardsPoint): EdwardsPoint {
  return { x: mod(-point.x), y: point.y, z: point.z, t: mod(-point.t) };
}

/**
 * Multiplies a point by a scalar.
 *
 * Double-and-add, most significant bit first, over a scalar already reduced mod
 * {@link ORDER}. Variable time by construction; see the module docs.
 *
 * @param point - the point to multiply.
 * @param scalar - a non-negative scalar, normally reduced with {@link reduceWideScalar}.
 */
export function scalarMult(point: EdwardsPoint, scalar: bigint): EdwardsPoint {
  let result = IDENTITY;
  let addend = point;
  let remaining = scalar;
  while (remaining > 0n) {
    if ((remaining & 1n) === 1n) result = addPoints(result, addend);
    addend = addPoints(addend, addend);
    remaining >>= 1n;
  }
  return result;
}

/**
 * Encodes a point in the canonical 32-byte form: little-endian `y`, with the low bit of `x`
 * in the most significant bit.
 *
 * @param point - the point to encode.
 */
export function compressPoint(point: EdwardsPoint): Uint8Array<ArrayBuffer> {
  const zInverse = inverse(point.z);
  const x = mod(point.x * zInverse);
  const y = mod(point.y * zInverse);
  const encoded = bigIntToBytesLE(y, 32);
  const sign = encoded[31];
  if (sign === undefined) throw new Ed25519Error('the encoding buffer is the wrong size');
  encoded[31] = (sign & 0x7f) | Number(x & 1n) << 7;
  return encoded;
}

/**
 * Decodes a point, refusing anything that is not a canonical encoding of a curve point.
 *
 * Strictness is not politeness here: a lenient decoder is how a non-canonical encoding, or a
 * point of small order, gets used in an exchange where both ends must agree on a value.
 * The Rust side refuses the same inputs.
 *
 * @param bytes - 32 bytes of compressed point.
 * @throws Ed25519Error when the length, the encoding, or the curve equation is wrong.
 */
export function decompressPoint(bytes: Uint8Array): EdwardsPoint {
  if (bytes.length !== 32) {
    throw new Ed25519Error(`a compressed point is 32 bytes, got ${bytes.length}`);
  }
  const y = bytesToBigIntLE(bytes) & ((1n << 255n) - 1n);
  if (y >= P) {
    throw new Ed25519Error('the encoding is not canonical: y is not reduced');
  }
  const signByte = bytes[31];
  if (signByte === undefined) throw new Ed25519Error('the encoding buffer is the wrong size');
  const sign = signByte >> 7;

  const ySquared = (y * y) % P;
  const numerator = mod(ySquared - 1n);
  const denominator = mod(D * ySquared + 1n);
  const candidate = numerator * inverse(denominator) % P;

  // p ≡ 5 (mod 8), so a square root is `a^((p+3)/8)` up to a factor of √−1.
  let x = power(candidate, (P + 3n) / 8n);
  if (x * x % P !== candidate) x = x * SQRT_M1 % P;
  if (x * x % P !== candidate) {
    throw new Ed25519Error('the encoding is not a point on this curve');
  }
  // `mod`, not a bare subtraction: for x = 0 the negation is p, which is the same field
  // element but not the same integer, and the "negative zero" check below would miss it.
  if (Number(x & 1n) !== sign) x = mod(P - x);
  // The all-zero x has a single encoding; the "negative zero" form is not a point.
  if (x === 0n && sign === 1) {
    throw new Ed25519Error('the encoding has a non-canonical sign bit');
  }
  return { x, y, z: 1n, t: mod(x * y) };
}

/**
 * Reduces 64 little-endian bytes to a scalar.
 *
 * This is `curve25519_dalek::Scalar::from_bytes_mod_order_wide`, which is also how the
 * Rust side turns random bytes into its ephemeral scalar. The pairing vectors pin them
 * together.
 *
 * @param bytes - 64 bytes, little-endian.
 */
export function reduceWideScalar(bytes: Uint8Array): bigint {
  if (bytes.length !== 64) {
    throw new Ed25519Error(`a wide scalar is 64 bytes, got ${bytes.length}`);
  }
  return bytesToBigIntLE(bytes) % ORDER;
}

/**
 * Reduces a big-endian byte string to a scalar.
 *
 * `spake2`'s `hash_to_scalar` reads its 48 HKDF bytes as a big-endian integer and then
 * reduces, which is *not* the same as reducing little-endian bytes: the two disagree on the
 * first exchange, and the failure looks like a wrong pairing code.
 *
 * @param bytes - the big-endian integer, as bytes.
 */
export function scalarFromBigEndian(bytes: Uint8Array): bigint {
  let value = 0n;
  for (const byte of bytes) value = (value << 8n) | BigInt(byte);
  return value % ORDER;
}

/** The curve order, exported so callers can reduce a scalar they built themselves. */
export const SCALAR_ORDER = ORDER;

/**
 * Reads little-endian bytes as a non-negative integer.
 *
 * @param bytes - the bytes to read.
 */
export function bytesToBigIntLE(bytes: Uint8Array): bigint {
  let value = 0n;
  for (let index = bytes.length - 1; index >= 0; index -= 1) {
    const byte = bytes[index];
    if (byte === undefined) throw new Ed25519Error('the buffer changed length while reading');
    value = (value << 8n) | BigInt(byte);
  }
  return value;
}

/**
 * Writes a non-negative integer as fixed-length little-endian bytes.
 *
 * @param value - the integer; it must fit.
 * @param length - how many bytes to produce.
 */
export function bigIntToBytesLE(value: bigint, length: number): Uint8Array<ArrayBuffer> {
  if (value < 0n) throw new Ed25519Error('a byte string cannot encode a negative number');
  if (value >> BigInt(length * 8) !== 0n) {
    throw new Ed25519Error(`${value} does not fit in ${length} bytes`);
  }
  const bytes = new Uint8Array(length);
  let remaining = value;
  for (let index = 0; index < length; index += 1) {
    bytes[index] = Number(remaining & 0xffn);
    remaining >>= 8n;
  }
  return bytes;
}

/**
 * Parses lower-case hex, for the fixed constants in this module.
 *
 * @param text - an even-length hex string.
 */
export function hexToBytes(text: string): Uint8Array<ArrayBuffer> {
  if (text.length % 2 !== 0) throw new Ed25519Error('hex must have an even length');
  const bytes = new Uint8Array(text.length / 2);
  for (let index = 0; index < bytes.length; index += 1) {
    const pair = text.slice(index * 2, index * 2 + 2);
    const value = Number.parseInt(pair, 16);
    if (Number.isNaN(value)) throw new Ed25519Error(`${pair} is not hex`);
    bytes[index] = value;
  }
  return bytes;
}

/**
 * Renders bytes as lower-case hex.
 *
 * @param bytes - the bytes to render.
 */
export function bytesToHex(bytes: Uint8Array): string {
  const parts: string[] = [];
  for (const byte of bytes) parts.push(byte.toString(16).padStart(2, '0'));
  return parts.join('');
}
