#!/bin/sh
# Generate self-contained curl-downloadable entrypoints from the common source.
set -eu
drdsh_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
for drdsh_scope in auto relay daemon; do
  case "$drdsh_scope" in auto) drdsh_file=$drdsh_root/install.sh ;; *) drdsh_file=$drdsh_root/$drdsh_scope/install.sh ;; esac
  {
    printf '#!/bin/sh\n# Generated by scripts/release-entrypoints.sh; edit scripts/release-install.sh.\n'
    printf 'DRDSH_COMPONENT=${DRDSH_COMPONENT:-%s}\n' "$drdsh_scope"
    sed '1d' "$drdsh_root/scripts/release-install.sh"
  } > "$drdsh_file"
  chmod +x "$drdsh_file"
done
